# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

 # Manual Testing
  workflow_dispatch:
    inputs:
        logLevel:
          description: 'Manual Run'     
          required: true
          default: 'warning'
        tags:
          description: 'Test Repo' 

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend
      
    steps:      
    - uses: actions/checkout@v2
    - name: Setup Node 
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
        cache-dependency-path: ./frontend/package-lock.json
    - run: npm ci
    - run: npm run build --if-present
